#sync-with-github:
#  before_script:
#    - git config --global user.name "${GITLAB_USER_NAME}"
 #   - git config --global user.email "${GITLAB_USER_EMAIL}"
  #script:
   # - git remote add github $REMOTE_REPOSITORY_URL
    #- git checkout master
    #- git pull origin master
    #- git pull github master
    #- git status
    # - git push http://root:$ACCESS_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git HEAD:master

stages:
  - test
  - backup
  - deploy

image: alpine

#simple unit test with composer
test_phpunit:
  image: composer:2
  stage: test
  script:
    - cd blog/
    - php vendor/bin/phpunit
    - echo "unit test complete"

#Deploy on heroku on when push on main
heroku_deploy:
  stage: deploy
  when: on_success
  only:
    - main
  script:
    - git push heroku main
    - echo "deploy complete."
