#sync-with-github:
#  before_script:
#    - git config --global user.name "${GITLAB_USER_NAME}"
 #   - git config --global user.email "${GITLAB_USER_EMAIL}"
  #script:
   # - git remote add github $REMOTE_REPOSITORY_URL
    #- git checkout master
    #- git pull origin master
    #- git pull github master
    #- git status
    # - git push http://root:$ACCESS_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git HEAD:master

stages:
  - build
  - test
  - backup
  - deploy

image: alpine

# maybe a build
build_a:
  stage: build
  script:
    - echo "This job builds something."

#simple unit test with composer
test_phpunit:
  image: composer:2
  stage: test
  script:
    - composer install
    - php vendor/bin/phpunit
    - echo "unit test complete"

#Backup Mirroring
github_backup:
  stage: backup
  script:
    - git push git@github.com:sulycate/ESN-mission-backup.git
    - echo "backup complete"

#Deploy on heroku on when push on main
heroku_deploy:
  stage: deploy
  when: on_success
  only:
    - main
  script:
    - git push heroku master
    - echo "deploy complete."
